### ISSUE TITLE
New hire options page

### ISSUE THREAD

**Issue by kpierduta** [kpierduta/deckerdence-website#33]
- [x] This should be the new layout as per Figma

- [x] We need to be able to add to the table in Sanity and select which option it is included in along with having the hover information 'i' where we can add what needs to be included

https://www.figma.com/file/u1FRFpWdm4jvaGHZjHJRSz/Deckerdence?node-id=494%3A42
![New Hire Options](https://user-images.githubusercontent.com/40568273/154355120-4bb783d1-68dc-4993-bbde-b863c3c4d466.png)

**Comment by dharmveer97** [comment]
https://deckerdence-dev.vercel.app/test/

**Comment by dharmveer97** [comment]
@gagansaini1212 design layout not matching icons and font-weight and font sizes as Figma.

- [ ] Could you please double-check whole website  colors, font-weights

**Comment by DCConnor** [comment]
Hi guys, @dharmveer97 @gagansaini1212 

**Desktop - Update** 

- [ ] Below the boxes aren't the same height as per the Figma design - please see below for reference 

![image](https://user-images.githubusercontent.com/100126342/155716010-65aea617-0207-4bf1-b496-24b7a5a4c51b.png)


- [ ] Table with key information doesn't match the design in Figma- only has two columns rather than three 

![image-1](https://user-images.githubusercontent.com/100126342/155716149-2e3b0252-be70-4474-8141-2899eafeddba.png)

Below the table, there is supposed to be buttons to learn more but is missing from the website at the moment - (Find more buttons in design) 

<img width="725" alt="image-2" src="https://user-images.githubusercontent.com/100126342/155716263-ab19209f-5eec-49a2-a56f-a02c7f015eff.png">


 **Mobile - update**

- [ ] The hero image and text are all squashed together on the mobile screen. Is it optimised for mobile?  Please see below for reference. 

![66dcd4f4-d491-4cc2-aca4-e0b781f52391_large](https://user-images.githubusercontent.com/100126342/155716489-f5f31ea0-34ce-4a9e-8d7c-faa6ce25ff9f.jpg)


- [ ] Also, both the tables don't fit on the whole screen and you have to scroll to the right to get the rest of the table - See screenshot below. 

![a8bd7a3d-d257-4b02-aa49-a3c989d61124_large](https://user-images.githubusercontent.com/100126342/155716588-e49e05ff-0cb1-4edc-925f-57e63973abd4.jpg)

Thank you :D

**Comment by gagansaini1212** [comment]
@kpierduta The last table issue, for the responsiveness in the mobile view it is scrollable.

**Comment by kpierduta** [comment]
Hi @gagansaini1212 
Could you review the following issues as above - they were ticked but they have not been completed:

- [ ] The boxes are still different sizes and haven't been lined up:


![image](https://user-images.githubusercontent.com/40568273/156372316-75c6fd9d-0e4d-4659-b514-56e9775962fa.png)

- [ ] The hero image text is still cramping up on the mobile version:


![image-1](https://user-images.githubusercontent.com/40568273/156372390-2b9fb455-c2ef-4d77-bcfd-b6f5e00d8575.png)

Thanks for your help
